name: Pushed to Dev Branch (Ridian)
run-name: ${{ github.actor }} has pushed to Dev Branch
on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          commit-message: Cloud - Update available list
          title: Cloud - Update available list
          body: Cloud - Update available list
          base: main
          labels: automated-pr, Clouds & Regions
          branch: dev
          delete-branch: false

