on:
    workflow_call:
      inputs:
        ref:
          required: true
          type: string
        save-coverage-badge:
          required: true
          type: boolean
jobs:
    run-quant-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          name: "Checkout quant-repo"
          with:
            ref: ${{ inputs.ref }}
  
        - name: "Authenticate to GCloud"
          uses: "google-github-actions/auth@v0"
          with:
            credentials_json: "${{ secrets.CI_CLOUD_RUN_QUANT_STAGING_KEY }}"
  
        - name: Install Python 3
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
  
        - name: Install keyrings.google-artifactregistry-auth (required for GCP artifact repo authentication)
          run: |
            python -m pip install --upgrade pip
            python -m pip install keyrings.google-artifactregistry-auth==1.1.1

        - name: Run coverage check.
          run: |
            echo "Python World"
            python -V